### ISSUE TITLE
Show detailed error message for images not available

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#399]
If a file is not available or duplicate it would sometimes be helpful if you would get a list of files instead of "Some files could not be accessed". If you have that list anyway we could display it (probably in a condensed way if is too long). If no files could be accessed display that instead. Not really top priority at the moment but a nice to have.

**Comment by mzur** [comment]
BIIGLE samples 5 images and if one of them cannot be accessed, the error is shown. So in the current implementation we could show the single file that could not be accessed. We can't check all files because that would take way too long. Would you still show the file that could not be accessed? You still wouldn't know if any of the other files are there or not.

**Comment by dlangenk** [comment]
I would still show it, as it could give a hint what is wrong (if this is not too big a deal to show it).

But you don't sample for duplicates do you?

**Comment by mzur** [comment]
> But you don't sample for duplicates do you?

No, validation for duplicates is done with all files.
