### ISSUE TITLE
Label swap does not update label color

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#493]
The feature is super cool but the label color in the ui is not updated on clicking a labeled object (tested with firefox and chrome on mac os). This would be helpful to not loose track of already swapped objects.

**Comment by mzur** [comment]
Clarification: The label swap tool is this one in the image/video annotation tool:

![image](https://github.com/biigle/core/assets/2457311/e5f17799-e179-4b0d-be33-5221e8980f96)

**Comment by mzur** [comment]
You mean the `updated_at` of the annotation? This issue originally was only about the UI that didn't refresh the color. Updating the timestamp is a nice idea but this should be done in a separate issue.

**Comment by lehecht** [comment]
I asked because this could help to fix this bug. Otherwise I will find another way to solve it.

**Comment by lehecht** [comment]
I can't identify the altered annotation(s), if I don't have the correct `updated_at` values.  The bug occurs because the swapped  annotation keeps its old id. [RefreshAnnotationSource](https://github.com/biigle/core/blob/45909ab1107cb1eb7d77cd82e31998b29ec00d1c/resources/assets/js/annotations/components/annotationCanvas.vue#L608-L633) uses annotations with new ids that exist only in the new map but not in the old one. 
One can refresh all annotations every time an annotation is changed, but this can create a lot of unnecessary work. Do you have any other ideas?

**Comment by mzur** [comment]
I think this issue boils down to the annotation not updating its color if a label is removed ([here](https://github.com/biigle/core/blob/e414e14573e57601d3d0206e9d33c8b9079f53d2/resources/assets/js/annotations/annotatorContainer.vue#L356-L357)). You are right that 1. this does not trigger a refresh (which is why the color isn't updated on label swap but also not if a label is deleted) and 2. the refresh method would not detect a change.

It should be ok to introduce a "hard" method call (in contrast to an updated Vue component property) to the annotationCavnas component to refresh an annotation in this case. This is similar to the [focusAnnotation()](https://github.com/biigle/core/blob/e414e14573e57601d3d0206e9d33c8b9079f53d2/resources/assets/js/annotations/annotatorContainer.vue#L351) method that is also directly called. When the [detachLabel](https://github.com/biigle/core/blob/e414e14573e57601d3d0206e9d33c8b9079f53d2/resources/assets/js/annotations/annotatorContainer.vue#L356C25-L356C25) API call succeeded, a refreshAnnotation() method of the annotationCanvas can be called to update the [feature color](https://github.com/biigle/core/blob/e414e14573e57601d3d0206e9d33c8b9079f53d2/resources/assets/js/annotations/components/annotationCanvas.vue#L395-L397). You can get a single annotation/feature with `this.annotationSource.getFeatureById(annotation.id)` ([ref](https://openlayers.org/en/v5.3.0/apidoc/module-ol_source_Vector-VectorSource.html#getFeatureById)).

You have to try if the OpenLayers map automatically refreshes if you update the color. Otherwise you have to call `this.map.render()` manually.
