### ISSUE TITLE
Problem with Bounding Boxes

### ISSUE THREAD

**Issue by aburfeid** [biigle/core#861]
https://github.com/biigle/reports/assets/102722054/d7aad3e6-1d6f-4d2e-bc66-b0948ebed699

Hi Martin,

I made a video, as since March there has been a change in the bounding boxes and if the Bounding Box is drawn first with a (relatively) straight up-down or down-up axis, the width changes randomly and is no longer attached to cursor movements. It worked in March, it does no longer, making annotation of randomly positioned diatoms quite difficult.

Thank you in advance.

Best wishes,

Andrea

**Comment by mzur** [comment]
I tracked this down to https://github.com/biigle/openlayers/pull/4 which likely introduced this bug. This was released in our patched OpenLayers version 5.3.2 but this was never used by BIIGLE due to a configuration error. The new version 5.3.3 was included as part of the annotation snapping feature, which includes the bogous changes of v5.3.2. I'm looking into it.

**Comment by mzur** [comment]
Hi @aburfeid, the fix is now live on biigle.de.

**Comment by aburfeid** [comment]
Hi @mzur thank you! That was fast :). Works like a charm now.
